### ISSUE TITLE
[Feature Request] Module Config Options & Routing

### ISSUE THREAD

**Issue by luxlogica** [getkirby-plugins/modules-plugin#21] opened 2017-08-04 01:18 UTC
Further to the suggestion in Issue #20, I thought it may be helpful if I set out also how Modules may be programatically different objects from Pages. Hopefully, this may help map out the implementation of Modules as a "first-class citizen" in Kirby 3! 

## Requirements

- Modules, like Pages, need to be able to have Controllers and Models: they are complex objects, with their own data sets and business logic that require a certain level of encapsulation, as mentioned in Issue #18 
- Modules should have their own section in the Panel Sidebar, as mentioned in Issue #20 
- Modules do not need to have sub-pages, but they need to have Files: anything that cannot be covered by the use of a structure field inside a module, should not be a module - i.e., it should be an independent page. Modules should only need to have Files - for self-contained display of image galleries, downloadable files, etc.
- Modules should not have a page-like URI, because they don't represent a page: they represent a section or part of a page. If I have a 'featuredproducts' module (section) inside a 'shop' page, then the expected, direct URL for that should be `http://example.com/shop#featuredproducts`.
- The developer needs to be able to specify custom HTML element, class and attributes that make up the parent (wrapper) element of the Module: this is a requirement in order to make the Module sufficiently flexible to be able to be used with a wide variety of CSS and Javascript UI frameworks and libraries.

## Modules Don't Need Sub-Pages
Because conceptually a Module is a section or part of a page, the use-cases covered by this design pattern imply that either:
  * the module will have only a small, sub-section of the content needed for the entire page
  * the module may have content that is particular to itself - images, text, downloadable files, and tabular data via Structure fields - but that content will not be as comprehensive as the content of an entire page, nor will it need its own encapsulated logic

So, a Module may need to have its own images, videos, and downloadable files, but it will never need to have its own sub-pages. The need for a sub-page is a clear indication that this is not a good candidate for a Module, and should likely be a Page of its own.

## Module Routing
Modules, like Pages, should have their own unique ID, which should correspond to a unique URL in the site. But that URL should reflect that the Module is merely an element, which is *part* of a Page. If "contact" is a Page, then it makes sense to have a `http://example.com/about-us/contact` URL in the site. But if clicking that URL takes me instead to a _section_ of the 'about-us' page, that is confusing. The expected URL for that scenario is `http://example.com/about-us#contact`.

## Module Configuration
Just as when we use the `kirbytext()` method, we get an automatic 'wrapper' element around the rendered content, so should the 'module()' method wrap the Module template with a container HTML element. However, in order for Modules to be able to be used flexibly with a wide variety of UI libraries and frameworks - e.g., Vue, React, Angular, as well as Bootstrap, Foundation and UIKit - there needs to be flexibility in the configuration of this wrapper element. In particular, we need to be able to specify:
  * which HTML element to use: a `<section>` may be appropriate sometimes, but in certain cases we may need to use a `<div>`, a `<ul>` or other, depending on the framework used.
  * custom CSS classes: most frameworks require the developer to use the framework's classes for formatting and targeting of the framework's javascript
  * custom attributes: many javascript frameworks and libraries require the developer to add data-* and other custom attributes for targeting and configuration of their javascript methods.

Therefore, ideally, the blueprint for Modules would have special configuration options to cover these cases - for instance:

``` yaml
title: Featured Products
element: section
class:
    - width-medium-6
    - width-large-4
    - container-center
attributes:
   - data-slideshow: 
        - animation: 'fade'
        - timing: 7000
files:
  [...]
fields:
  [...]
```

This would generate a wrapping element like this:

``` html
<section 
    id="featured_products" 
    class="width-medium-6 width-large-4 container-centre" 
    data-slideshow="{animation: 'fade', timing: 7000}">

   <!-- Module template goes here -->

</section>
```

**Comment by lukaskleinschmidt** [comment] 2017-08-04 13:45
I can not agree with all of your points. Actually mostly everything (except for controllers and the sidebar section) is possible to do right now without too much hassle.

I don't like the idea of having a too strict module structure. When you dont need subpages just disable them in the blueprint. The wrapper can just live in the module html file I guess?! For routing you can easily use a model to overwrite the url method.

```php
class ModuleGalleryPage extends Kirby\Modules\ModulePage {
  public function url() {
    return $this->page()->url() . '/#' . $this->uid();
  }
}
```

That sounded harder than wanted. I'm not trying to rant here 🙂 
Especially models and controllers inside the module directory would be great.
But I think some of your suggestions are not neccessary because they can easily be implemented and would on the other side restrict the usage of modules in some use cases.

**Comment by luxlogica** [comment] 2017-08-04 22:47
@lukaskleinschmidt Thank you for the feedback! A couple of points to note:

The controller-based solution to routing Modules to a `#`-based URL would only overload the `url()` method, but would not actually _route_ to the module - i.e., if someone tries to access `http://example.com/products#gallery` it would still trigger the controller+model of the parent page, and not the module's. For that we actually need to change Kirby's Router, which may not be a trivial task.

In regards to allowing sub-pages in modules: this adds many unnecessary architectural issues to the system, and several layers of complexity (which would only delay the release of the feature) - for instance
  - if modules have `#`-based URLs, and you want to have sub-pages inside modules, then what would be the URL of those sub-pages? 
  - if modules have sub-pages, will these sub-pages be allowed to have their own modules and module sub-pages, which in turn can have their own modules and module sub-pages? If so, these will create programming and usability issues - think for instance of the URL issue above. 

If we _don't_ allow module sub-pages to have their own modules, then we will need to create a subclass of Page - and possibly a more complex Module, which will be more unnecessary coupled with the Page. Either solution - allowing or not allowing module sub-pages to have their own modules - implies a noticeable increase in complexity and management - both for us and the users. 

But more to the point: I don't think you are sacrificing any flexibility by not allowing sub-pages for modules. Modules, as proposed, cover a very specific design pattern which is _not yet_ covered by either Pages or Snippets. If the data structures you're working with inside a module require the full complexity of a sub-page, then it's likely you actually need a Page, not a Module. 

Lastly, I do agree with you, that the extra configuration options for the Module wrapper element could be handled directly in the Module template - and this would actually keep the Module even more dynamic, and flexible - and hopefully, this would mean also less programming for the Kirby team, and a faster release date for us!

**Comment by lukaskleinschmidt** [comment] 2017-08-05 09:32
I'm not sure I got this right. But if I go to `http://example.com/products#gallery` assuming that the `gallery` is  a module of  `products`. Wouldn't it be the expected behaviour that the `products` controller+model are triggered as well as the `gallery` model (and controller if it would work) for the `gallery`module?

I'm currently working on a project with modules containing subpages. I dont' use them as subpages more like a data storage I agree with you that using them as real subpages would not make alot of sense.
But it all depends on the way how someone wants to utilize subpages. I would still argue just not to use subpages if you dont' need them. It all depends on how you set up your blueprints.

Also I don't think that subpages inside modules add any complexity. In the end every folder inside kirby is a page or module or whatever you want it to be. Models are already working (although you have to place them in `site/models/module.gallery.php` right now). The only missing part right now is the controller.

**Comment by luxlogica** [comment] 2017-08-05 10:08
> I'm not sure I got this right. But if I go to http://example.com/products#gallery assuming that the gallery is a module of products. Wouldn't it be the expected behaviour that the products controller+model are triggered as well as the gallery model (and controller if it would work) for the gallerymodule?

That is correct - that is what I'd hope for, too.

> Also I don't think that subpages inside modules add any complexity.

They would likely add *a lot* of complexity, indeed - look at the question I raised above of what to do about URLs of modules and their sub-pages... But more to the point: module sub-pages are just not needed, as we already have the flexibility they would provide simply by using Pages, structure fields and snippets. 😉

**Comment by lukaskleinschmidt** [comment] 2017-08-05 10:17
I totally agree that using pages inside modules as actual subpages does not make alot of sense.
But using pages inside modules as some kind of data storage without the purpose to be publicly accessible is in my opinion a real use case.

**Comment by luxlogica** [comment] 2017-08-05 10:29
@lukaskleinschmidt I'm really curious about this - because I think you are seeing a use-case that my little tired brain is missing... It seems to me, that if you just want to store data - even complex data - you could simply use a structure field. Is this a matter of simply being able to *hide* the data?

**Comment by lukaskleinschmidt** [comment] 2017-08-05 10:56
In my use case I used the modules to choose a layout. (E.g fullwidth module, module with sidebar and some more). Inside the module with the modeuls I have the option to insert different sub modules like text, a cta, forms, images and so on.
I konw that this could be done with the builder field or something similar but I would miss the option for copy and paste (sortable field) and the possebility to use models. Also I like the that the subpage approach is cleaner when you have a lot of content modules with alot of files and/or many options.

**Comment by lukasbestle** [comment] 2017-08-13 18:47
I agree with @lukaskleinschmidt here. Adding a lot of complexity like wrapper HTML etc. isn't going to work for this plugin. Kirby was designed to be simple and to be compatible with all content structures and markup. Breaking that in this plugin isn't intended.

I see your points in #18 about controllers/models though. I also want to implement those, that's why I created the issue in the first place.

Because of the many different feature requests in this issue, it is hard to keep track of the features, I'm therefore closing this. Please reopen smaller issues for the features you still think are useful.


I see your points in #18 about controllers/models though. I also want to implement those, that's why I created the issue in the first place.

Because of the many different feature requests in this issue, it is hard to keep track of the features, I'm therefore closing this. Please reopen smaller issues for the features you still think are useful.

**Closed by lukasbestle** 2017-08-13 18:47 UTC

**Comment by luxlogica** [comment] 2017-08-18 04:44
@lukaskleinschmidt our vision is not that dissimilar:

> In my use case I used the modules to choose a layout. (E.g fullwidth module, module with sidebar and some more). Inside the modules I have the option to insert different sub modules like text, a cta, forms, images and so on.

For 'single elements' such as a cta-button, or a media object, IMHO a snippet would be more appropriate than a module. It seems to me that modules represent conceptually an entire sub-section of a page, which may contain several of these elements. A module might, for instance, represent a 'hero banner', and inside that module we may provide the client with the ability to choose from several different cta-buttons - and that choice would trigger a different snippet to load in the template.

> I konw that this could be done with the builder field or something similar but I would miss the option for copy and paste (sortable field) and the possebility to use models. 

I'm not too sure I understand what you mean by 'miss the option for copy and paste', but I totally agree that modules should have both *models* and *controllers*. 

>  Also I like the that the subpage approach is cleaner when you have a lot of content modules with alot of files and/or many options.

If modules have their own section in the sidebar, as proposed in Issue #20, and have models and controllers, as proposed in Issue #18, then they will cover the use-cases you describe - and there will be no need for them to have sub-pages. As I said: if you need anything more complicated than that - e.g., multiple hierarchical levels of sub-pages and modules - then you probably should be using a Page directly.

@lukasbestle I think we're all in agreement that HTML wrapper elements, etc. was a bad idea. Issue #20 already covers the sidebar section for Modules, and issue #18 covers the need for controllers and modules. The only thing left from our list here then is the request to have special ('#-based') URLs - and routing - for the modules. I'll put that on a separate issue, and then we're covered!
